spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/mm_online_shop
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081


